Import Union from typing
This looks like a typo where Union is being imported from `git` instead of `typing` like elsewhere in the repo.

I do not have GitPython installed in my container, so this was erroring:

```from git import Union
ModuleNotFoundError: No module named 'git'```